nines_feedback:
    default_status: Name 1
    public_status: Name 2
    subject: New feedback received
    sender: noreply@example.com
    recipients:
        - user@example.com
        - another@example.com
