nines_user:
    roles: [ ROLE_ADMIN, ROLE_USER_ADMIN, ROLE_BLOG_ADMIN, ROLE_COMMENT_ADMIN, ROLE_CONTENT_ADMIN, ROLE_USER ]
    after_login_route: homepage
    after_request_route: homepage
    after_reset_route: nines_user_security_login
    after_logout_route: homepage
