# config/routes.yaml
nines_blog:
    resource: '@NinesBlogBundle/config/routes.yaml'

nines_editor:
    resource: '@NinesEditorBundle/config/routes.yaml'
    prefix: editor

nines_user:
    resource: '@NinesUserBundle/config/routes.yaml'
